---
keystore:
  token:
    type: jks
    location: "classpath:token_keystore.jks"
    password: ${keystore.token.store_password}
    keyAlias: ${keystore.token.key_alias}
    keyPassword: ${keystore.token.key_password}
defaults:
  token:
    expiration: P2D
    issuer: sample-app-spring-boot
auth:
  basic:
    username: user
    password: secret
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 100ms, 400ms, 500ms, 2000ms
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99
        