package com.sap.hcp.cf.logging.sample.springboot.controller;

import com.sap.hcp.cf.logging.sample.springboot.service.DynamicLogLevelAlgorithmProvider;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.interfaces.RSAPublicKey;
import java.util.Base64;

/**
 * This controller provides an endpoint to get the public key used for signing the tokens generated by the
 * {@link TokenController}.
 */
@RestController
public class PublicKeyController {

    /**
     * Returns the public key in Base64 encoding used to sign the JWTs created by the {@link TokenController}.
     *
     * @return
     */
    @GetMapping("/publickey")
    public String getPublicKey() {
        RSAPublicKey publicKey = (RSAPublicKey) DynamicLogLevelAlgorithmProvider.getKeyPair().getPublic();
        return Base64.getEncoder().encodeToString(publicKey.getEncoded());
    }

}
