name: Maven Verify

on:
  pull_request:
    branches:
      - main
      - release-4

jobs:
  build-main:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clean with Maven
        run: mvn clean
      - name: Build with Maven
        run: mvn verify

  build-releas-4:
    if: github.base_ref == 'release-4'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean verify
